name: typing_text_demo
description: "An example app demonstrating the typing_text package."
version: 1.0.1+2
publish_to: 'none'

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  typing_text:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # If your example app has assets or fonts, specify them here
  # assets:
  #   - assets/some_asset.png
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Italic.ttf
  #         style: italic
